In [16]:
import pandas as pd

# Read the dataset first
df = pd.read_csv("../data/raw/retail_customer_churn_100k (1).csv")

# Display dataset information
print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

# Display first five records
df.head()

Dataset loaded successfully!
Number of rows: 100000
Number of columns: 18

,customer_id,age_group,gender,region,customer_segment,preferred_channel,purchase_frequency,avg_order_value,total_spent,recency_days,website_visits,discount_usage_rate,email_open_rate,cart_abandonment_rate,loyalty_score,engagement_score,churn_risk,churn_flag
0,C000001,18-24,Other,North,Loyal,Online,5,381.27,2108.80,189,27,0.38,0.13,0.42,33,35.5,Medium,1
1,C000002,25-34,Other,South,New,Mobile App,12,376.65,3843.06,277,68,0.51,0.06,0.07,68,49.5,Medium,1
2,C000003,55+,Other,North,VIP,Online,5,37.73,224.65,271,23,0.64,0.22,0.46,73,38.0,High,1
3,C000004,18-24,Male,North,Returning,Mobile App,12,191.19,1960.79,89,93,0.66,0.31,0.13,93,59.0,Low,0
4,C000005,55+,Other,North,Returning,Mobile App,2,279.64,594.79,264,4,0.73,0.27,0.58,11,34.5,High,1

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df.head()

,customer_id,age_group,gender,region,customer_segment,preferred_channel,purchase_frequency,avg_order_value,total_spent,recency_days,website_visits,discount_usage_rate,email_open_rate,cart_abandonment_rate,loyalty_score,engagement_score,churn_risk,churn_flag
0,C000001,18-24,Other,North,Loyal,Online,5,381.27,2108.80,189,27,0.38,0.13,0.42,33,35.5,Medium,1
1,C000002,25-34,Other,South,New,Mobile App,12,376.65,3843.06,277,68,0.51,0.06,0.07,68,49.5,Medium,1
2,C000003,55+,Other,North,VIP,Online,5,37.73,224.65,271,23,0.64,0.22,0.46,73,38.0,High,1
3,C000004,18-24,Male,North,Returning,Mobile App,12,191.19,1960.79,89,93,0.66,0.31,0.13,93,59.0,Low,0
4,C000005,55+,Other,North,Returning,Mobile App,2,279.64,594.79,264,4,0.73,0.27,0.58,11,34.5,High,1

In [19]:
df.tail()

,customer_id,age_group,gender,region,customer_segment,preferred_channel,purchase_frequency,avg_order_value,total_spent,recency_days,website_visits,discount_usage_rate,email_open_rate,cart_abandonment_rate,loyalty_score,engagement_score,churn_risk,churn_flag
99995,C099996,25-34,Male,Central,Loyal,In-Store,8,363.84,2596.84,191,54,0.72,0.10,0.30,67,40.0,Low,0
99996,C099997,25-34,Other,West,New,In-Store,2,195.94,337.17,104,5,0.59,0.05,0.28,51,38.5,Low,0
99997,C099998,18-24,Male,Central,Loyal,Mobile App,2,40.53,93.39,150,11,0.44,0.63,0.31,59,66.0,Low,0
99998,C099999,25-34,Male,Central,VIP,Online,12,173.99,2476.75,201,70,0.70,0.39,0.67,72,36.0,Medium,0
99999,C100000,35-44,Female,Central,Loyal,In-Store,8,223.49,1758.39,321,61,0.76,0.44,0.14,47,65.0,High,1

In [20]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of rows: 100000
Number of columns: 18

In [21]:
for i, column in enumerate(df.columns, 1):
    print(f"{i:02d}. {column}")

01. customer_id
02. age_group
03. gender
04. region
05. customer_segment
06. preferred_channel
07. purchase_frequency
08. avg_order_value
09. total_spent
10. recency_days
11. website_visits
12. discount_usage_rate
13. email_open_rate
14. cart_abandonment_rate
15. loyalty_score
16. engagement_score
17. churn_risk
18. churn_flag

In [22]:
df.dtypes

customer_id                  str
age_group                    str
gender                       str
region                       str
customer_segment             str
preferred_channel            str
purchase_frequency         int64
avg_order_value          float64
total_spent              float64
recency_days               int64
website_visits             int64
discount_usage_rate      float64
email_open_rate          float64
cart_abandonment_rate    float64
loyalty_score              int64
engagement_score         float64
churn_risk                   str
churn_flag                 int64
dtype: object

In [23]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   customer_id            100000 non-null  str
 1   age_group              100000 non-null  str
 2   gender                 100000 non-null  str
 3   region                 100000 non-null  str
 4   customer_segment       100000 non-null  str
 5   preferred_channel      100000 non-null  str
 6   purchase_frequency     100000 non-null  int64
 7   avg_order_value        100000 non-null  float64
 8   total_spent            100000 non-null  float64
 9   recency_days           100000 non-null  int64
 10  website_visits         100000 non-null  int64
 11  discount_usage_rate    100000 non-null  float64
 12  email_open_rate        100000 non-null  float64
 13  cart_abandonment_rate  100000 non-null  float64
 14  loyalty_score          100000 non-null  int64
 15  engagement_score       100000 non-null  float64
 16  churn_risk             100000 non-null  str
 17  churn_flag             100000 non-null  int64
dtypes: float64(6), int64(5), str(7)
memory usage: 17.4 MB

In [24]:
missing = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean() * 100
})

missing = missing.sort_values(
    "Missing_Count",
    ascending=False
)

missing

                       Missing_Count  Missing_Percentage
customer_id                        0                 0.0
age_group                          0                 0.0
gender                             0                 0.0
region                             0                 0.0
customer_segment                   0                 0.0
preferred_channel                  0                 0.0
purchase_frequency                 0                 0.0
avg_order_value                    0                 0.0
total_spent                        0                 0.0
recency_days                       0                 0.0
website_visits                     0                 0.0
discount_usage_rate                0                 0.0
email_open_rate                    0                 0.0
cart_abandonment_rate              0                 0.0
loyalty_score                      0                 0.0
engagement_score                   0                 0.0
churn_risk                         0                 0.0
churn_flag                         0                 0.0

In [25]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 0

In [26]:
duplicate_customer_ids = df["customer_id"].duplicated().sum()

print("Duplicate customer IDs:", duplicate_customer_ids)

Duplicate customer IDs: 0

In [27]:
unique_summary = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[col].nunique() for col in df.columns]
})

unique_summary

                   Column  Unique Values
0             customer_id         100000
1               age_group              5
2                  gender              3
3                  region              5
4        customer_segment              4
5       preferred_channel              3
6      purchase_frequency              9
7         avg_order_value          35250
8             total_spent          86590
9            recency_days            364
10         website_visits            478
11    discount_usage_rate             76
12        email_open_rate             86
13  cart_abandonment_rate             81
14          loyalty_score             90
15       engagement_score            165
16             churn_risk              3
17             churn_flag              2

In [28]:
categorical_columns = df.select_dtypes(
    include=["object"]
).columns

for column in categorical_columns:
    print("\n" + "=" * 50)
    print(column)
    print(df[column].value_counts())

==================================================
customer_id
customer_id
C000001    1
C000002    1
C000003    1
C000004    1
C000005    1
          ..
C099996    1
C099997    1
C099998    1
C099999    1
C100000    1
Name: count, Length: 100000, dtype: int64

==================================================
age_group
age_group
35-44    20109
45-54    20093
18-24    19987
25-34    19929
55+      19882
Name: count, dtype: int64

==================================================
gender
gender
Male      33434
Female    33367
Other     33199
Name: count, dtype: int64

==================================================
region
region
East       20240
West       20039
North      20035
Central    20012
South      19674
Name: count, dtype: int64

==================================================
customer_segment
customer_segment
New          25113
Returning    25106
VIP          24906
Loyal        24875
Name: count, dtype: int64

==================================================
preferred_channel
preferred_channel
Online        33430
In-Store      33303
Mobile App    33267
Name: count, dtype: int64

==================================================
churn_risk
churn_risk
Low       40141
High      32410
Medium    27449
Name: count, dtype: int64

C:\Users\USER\AppData\Local\Temp\ipykernel_20372\1129359364.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(